### ISSUE TITLE
Statuses compatibility with mastodon API

### ISSUE THREAD

**Issue by zeerooth** [kitsune-soc/kitsune#304]
Extension of https://github.com/kitsune-soc/kitsune/issues/3

We're missing most of the components of the status API, mainly:
- [ ] #309
- [x] [See who boosted a status](https://docs.joinmastodon.org/methods/statuses/#reblogged_by) (#367)
- [x] [See who favourited a status](https://docs.joinmastodon.org/methods/statuses/#favourited_by) (#367)
- [x] [Boost a status](https://docs.joinmastodon.org/methods/statuses/#boost) (#306)
- [x] [Undo boost of a status](https://docs.joinmastodon.org/methods/statuses/#unreblog) (#306)
- [ ] [Bookmark a status](https://docs.joinmastodon.org/methods/statuses/#bookmark)
- [ ] [Undo bookmark of a status](https://docs.joinmastodon.org/methods/statuses/#unbookmark)
- [ ] [Mute a conversation](https://docs.joinmastodon.org/methods/statuses/#mute) (requires https://github.com/kitsune-soc/kitsune/issues/149)
- [ ] [Unmute a conversation](https://docs.joinmastodon.org/methods/statuses/#unmute) (requires https://github.com/kitsune-soc/kitsune/issues/149)
- [ ] [Pin status to profile](https://docs.joinmastodon.org/methods/statuses/#pin)
- [ ] [Unpin status from profile](https://docs.joinmastodon.org/methods/statuses/#unpin)
- [x] [Edit a status](https://docs.joinmastodon.org/methods/statuses/#edit) (#306)
- [ ] [View edit history of a status](https://docs.joinmastodon.org/methods/statuses/#history) (requires https://github.com/kitsune-soc/kitsune/issues/330)
- [x] #310

**Comment by Zeerooth** [comment]
@aumetra could you please assign this one to me? I'll get started on the key endpoints here

**Comment by aumetra** [comment]
I'm going to (very sneakily) steal myself the issues for status translation and for "View status source", if that's okay with you
